FROM golang

# RUN apk --no-cache add git bash go make gcc sqlite
RUN mkdir -p /go/src /go/pkg /go/bin && chmod -R 777 /go

# ENV GOROOT /usr/lib/go
ENV GOPATH /go
ENV PATH $GOPATH/bin:$PATH

ADD Makefile /go/src/github.com/iancullinane/pesto-app/Makefile
ADD server/ /go/src/github.com/iancullinane/pesto-app/server/

WORKDIR /go/src/github.com/iancullinane/pesto-app

# CMD ["ls", "-la"]
RUN ["go", "get", "./..."]
RUN go install ./...
CMD ["make", "go-build"]

